add ultravnc single click prompt
rfbproto/rfbproto pull request #16
Opened 2018-10-17 03:37 UTC by secureinfo

I'm not good at English.

2018-10-19 13:10 UTC, CendioOssman requested changes
Thanks for your contribution. There is unfortunately still not quite clear how to use this extension. Please have a look at the comments and see if you can make it more obvious for someone implementing a client or server.

2018-10-19 13:10 UTC, CendioOssman commented on rfbproto.rst
> +107         `UltraVNC Single Click Prompt`_
Hmmm.... I'm looking at the IANA link and this number isn't registered. If UltraVNC are using it without any other handshake then they really need to register it. Do they have other authentication numbers they use? We need to have this allocated with IANA before we can start recommending it to more implementations.

2018-10-19 13:10 UTC, CendioOssman commented on rfbproto.rst
> +..                      -1          restart
The status is unsigned, so for clarity I think it is better to write this as `0xffffffff`.

2018-10-19 13:10 UTC, CendioOssman commented on rfbproto.rst
> +..                      -1          restart
We don't really have an allocation policy for these. I think we need to mail IANA and see if they can set up a registry. We don't want to have conflicts here.

2018-10-19 13:10 UTC, CendioOssman commented on rfbproto.rst
> +..                      -1          restart
How is this restart defined? What should a client do when it sees this result?

2018-10-19 13:10 UTC, CendioOssman commented on rfbproto.rst
> +4                          ``U32``       *prompt-length*
Didn't you state that this is in little-endian in your PR to noVNC?

2018-10-19 13:10 UTC, CendioOssman commented on rfbproto.rst
> +*prompt-length*            ``U8`` array  *prompt-string*
And what is in this? What should the client do with it?

2018-10-19 13:10 UTC, CendioOssman commented on rfbproto.rst
> +The client sends a non-zero value to accept.
Why does the client need to accept something?

2018-10-20 07:28 UTC, secureinfo commented on rfbproto.rst
> +..                      -1          restart
The server will resend some new authentication types to be selected by the client and then continue the authentication process.

2018-10-23 14:01 UTC, CendioOssman commented on rfbproto.rst
> +107         `UltraVNC Single Click Prompt`_
Let's start with the allocations and deal with the behaviour separately. Can you mail IANA and get these numbers allocated? A quick glance suggests that UltraVNC has laid claim to the entire `0x68` to `0x7f` range.

2018-10-23 14:02 UTC, CendioOssman commented on rfbproto.rst
> +..                      -1          restart
You don't need to be a UltraVNC developer in these cases. Just tell IANA that you've found that UltraVNC uses these numbers and that they should be noted in their lists. I've done that in the past without issue. :)

2018-10-23 14:04 UTC, CendioOssman commented on rfbproto.rst
> +..                      -1          restart
The question is if this is really a "restart", or a "continue". I.e. should the client throw away any information already agreed upon? Or is it a request for the server for several steps?

2019-01-11 13:45 UTC, CendioOssman commented
@secureinfo, are you still looking at getting this completed?

2019-02-15 10:01 UTC, CendioOssman commented
No response. Closing.

2019-02-15 10:01 UTC, closed without merging

2025-06-04 00:46 UTC, Neustradamus commented
@RudiDeVos: Have you seen this PR and comments?