Clarify that encoding -261 (LED State) is from the QEMU range
rfbproto/rfbproto pull request #30
Opened 2020-09-01 14:35 UTC by berrange

Encodings -257 to -272 are a range assigned to the QEMU project.

This also distinguishes it more explicitly from the similar
VMWare LED state encoding.

Signed-off-by: Daniel P. Berrangé <berrange@redhat.com>

2020-09-03 08:19 UTC, CendioOssman commented
I'm a bit opposed to the first rationale as I think we should have a spirit of cooperation rather than reserving extensions for specific projects. But I agree with the second part about avoiding confusion with the similar extension developed by VMware.

2020-09-03 08:21 UTC, CendioOssman requested changes
It seems there are more references to the old name as I get errors when trying to generate documents:

```
./rsttool rst2html "rfbproto.rst" "rfbproto.html"
rfbproto.rst:1277: (ERROR/3) Unknown target name: "led state pseudo-encoding".
```

2020-09-03 08:40 UTC, berrange commented
I didn't consider this naming to imply  non-co-operation, rather it is just a reflection of the way certain ranges of numbers were assigned to certain projects to define usage of. All the other encodings we've defined are named according to this same scheme. Co-operation between projects is inherently implied by virtue of us defining this collaborative spec.

2020-09-09 15:36 UTC, berrange commented
I pushed the update, but can't dismiss the "1 change request" message

2020-09-15 07:01 UTC, CendioOssman approved these changes
Sorry about that. I missed that you also made a push.

2020-09-15 07:10 UTC, merged