Document the SASL security type
rfbproto/rfbproto pull request #31
Opened 2020-09-01 15:30 UTC by berrange

This security type was implemented by QEMU (server side) and GTK-VNC
(client side), using Cyrus-SASL as the supporting library. These impls
are considered the reference implementations from which this protocol
specification was then written.

This was previously submitted 10 years ago on the mailing list

https://www.mail-archive.com/tigervnc-rfbproto@lists.sourceforge.net/msg00259.html

and for some reason I forgot to ever re-submit.

The original spec had a crazy flaw in it too - it documented a "continue-flag" taking values 1 (continue another step), and 0 (finished SAL). It should have had the exact opposite,  a "complete-flag" taking values 0 (continue another step), and 1 (finished SAL).

2020-09-03 08:30 UTC, CendioOssman requested changes
Looks mostly good, thanks. But I have some concerns that I've noted.

2020-09-03 08:30 UTC, CendioOssman commented on rfbproto.rst
> +  ANONYMOUS,KERBEROS_V4,DIGEST-MD5
I'm afraid I'm no too familiar with SASL. Are these guaranteed to be ASCII or do we have an encoding ambiguity here?

2020-09-03 08:30 UTC, CendioOssman commented on rfbproto.rst
> +                     &mechlist, NULL, NULL);
Somethings off with the indentation here.

2020-09-03 08:30 UTC, CendioOssman commented on rfbproto.rst
> +with *clientout-length* equal to 0.
It sounds like these things should be treated as opaque blobs, not strings. So perhaps avoid talking about terminating `\0`s?

2020-09-03 08:30 UTC, CendioOssman commented on rfbproto.rst
> +         write_u8(clientout, strlen(clientout) + 1)
This looks wrong since it seems to do the mistake of seeing everything as strings. `sasl_client_start()` gives you an exact length of the data. Why not use that instead of trying to figure it out yourself?

2020-09-03 08:30 UTC, CendioOssman commented on rfbproto.rst
> +`SASL client step message`_.
There's a lot of duplication here. Can we merge some of this together better?

2020-09-03 08:57 UTC, berrange commented on rfbproto.rst
> +  ANONYMOUS,KERBEROS_V4,DIGEST-MD5
Mechanism names are standardized in various RFCs. I believe they've only ever used ASCII for them and can't imagine a reason why they'd need to use 8-bit chars of any kind

2020-09-28 14:11 UTC, berrange commented on rfbproto.rst
> +         write_u8(clientout, strlen(clientout) + 1)
There is some complication here because I'm trying to define the behaviour that matches the actual implementation done by QEMU and GTK-VNC. They probably should have treated things as opaque, but in practice they're sending an extra tailing \0 in most cases. This example code doesn't entirely match what they do though, so I'll try to redo this again.

2020-09-29 07:01 UTC, CendioOssman commented on rfbproto.rst
> +         write_u8(clientout, strlen(clientout) + 1)
I can understand wanting to match existing implementations, but SASL is an already established thing outside of QEMU/GTK-VNC. So if that implementation is incompatible with other ones, then we really should think about a strategy to get that fixed. Having "I can't believe it's not real SASL" is just asking for issues, given how much GSS abstracts things away.

2024-08-13 08:30 UTC, berrange commented on rfbproto.rst
> +  ANONYMOUS,KERBEROS_V4,DIGEST-MD5
The RFC limits them to A-Z, 0-9, - & _

2024-09-11 17:12 UTC, berrange commented on rfbproto.rst
> +with *clientout-length* equal to 0.
Yes, we need to treat them as opaque binary blobs. What I was trying (and failing) to correctly describe is that when "clientout-data" is non-NULL, we pad the length & data sent on the wire with an extra NUL byte. This was based on the belief that when de-serializing we want to preserve the distinction between ``clientout-data==NULL + clientout-len==0`` and ``clientout-data==non-NULL + clientout-len==0``.

For mechanisms where the data is purely binary there is no such distinction, as `clientout-data==non-NULL + clientout-len==0`` is conceptually invalid. For mechanisms where the data is actually a string, `clientout-data==non-NULL + clientout-len==0`` could indicate an empty string, which is technically distinct from a NUL string. 

It is unclear in retrospect whether this actually matters to mechanisms in reality, but this is the way I designed & implemented the SASL security type spec, and so we need to keep this extra NUL padding otherwise we break compatibility, and would have to request a brand new security type allocation.

I've re-written the text significantly to try to clarify this better.

2024-09-11 17:13 UTC, berrange commented on rfbproto.rst
> +`SASL client step message`_.
I've cut out some of the duplicated text, by referring back to earlier paragraphs.

2024-09-11 17:13 UTC, berrange commented
> @berrange, still interested in getting this finished? :)

I've pushed an update of this spec addition

2024-09-18 10:58 UTC, CendioOssman commented on rfbproto.rst
> +with *clientout-length* equal to 0.
Looks good!

2024-09-18 11:00 UTC, CendioOssman commented on rfbproto.rst
> +         write_u8(clientout, strlen(clientout) + 1)
I guess this pseudo-code needs to be updated as well.

Or perhaps just omit it? I think the description is clear enough without it.

2024-09-18 11:01 UTC, CendioOssman commented on rfbproto.rst
> +         write_u8(clientout, strlen(clientout) + 1)
Same thing with the other pseudo-code, I guess.

2024-09-18 11:04 UTC, CendioOssman commented on rfbproto.rst
> +determine whether the server considers the negotiation successful.
What happens if the client is happy, but the server is not? Is the `SecurityResult` message encrypted or not?

2024-09-18 11:04 UTC, CendioOssman commented on rfbproto.rst
> +determine whether the server considers the negotiation successful.
Never mind, I re-read the previous paragraph better. :)

2024-09-18 11:05 UTC, CendioOssman commented
I think this is looking really good now! Can we just get that pseudo-code looked at, and we should be ready to merge.

2024-09-18 14:35 UTC, CendioOssman commented on rfbproto.rst
> +         write_u8(clientout, strlen(clientout) + 1)
I think so, yes. If nothing else, information in two places carries the risk of being out of sync. At which point it becomes less clear instead of more. :)

2024-09-19 11:56 UTC, berrange commented
Re-pushed with redundant code snippets removed.

2024-09-20 08:47 UTC, CendioOssman approved these changes
Great! Thanks for getting this finished!

2024-09-20 08:47 UTC, merged