Pi-KVM H.264 Encoding
rfbproto/rfbproto pull request #39
Opened 2021-02-04 12:34 UTC by mdevaev

The story:
- https://github.com/TigerVNC/tigervnc/issues/1187

The reference implementation:
- https://github.com/TigerVNC/tigervnc/pull/1194

2021-02-04 12:41 UTC, CendioOssman commented
Great. I'll try to have a look soon. 

Is there also code ready in Pi-KVM that can be referenced?

2021-02-04 12:51 UTC, mdevaev commented
Of course.

Here the RFB implementation: https://github.com/pikvm/kvmd/blob/master/kvmd/apps/vnc/rfb/__init__.py#L171

VNC server: https://github.com/pikvm/kvmd/blob/master/kvmd/apps/vnc/server.py

H264 compressor: https://github.com/pikvm/ustreamer/tree/master/src/ustreamer/h264

The server and the encoder work asynchronously. The H.264 stream is generated by a single encoder, and multiple VNC clients can receive this stream. Simpler thirdparty server implementations with synchronous encoding will also be able to implement this protocol just as easily. They don't even have to do frame gluing.

2021-02-08 11:26 UTC, CendioOssman requested changes
Looks very nice. But I have a few things that would be nice to get clarified.

2021-02-08 11:26 UTC, CendioOssman commented on rfbproto.rst
> +size will be used to find the decoder context in the client.
It's each rect that has coordinates.

2021-02-08 11:26 UTC, CendioOssman commented on rfbproto.rst
> +wants to send an H.264 data, the *FrameBufferUpdate* coordinates and
"data" looks weird here. Did you mean to write "rectangle"?

2021-02-08 11:26 UTC, CendioOssman commented on rfbproto.rst
> +a new one. The **ResetAllContexts** flag deletes all client contexts.
Before decoding the data in the rect? Or after?

2021-02-08 11:26 UTC, CendioOssman commented on rfbproto.rst
> +as a control message and apply the *flags*.
I assume this is to signal the end of a stream?

2021-02-08 11:26 UTC, CendioOssman commented on rfbproto.rst
> +parsed as a regular H.264 stream.
Can the server send partial frames?

2021-02-08 11:26 UTC, CendioOssman commented on rfbproto.rst
> +I-frame. However, the client should not ignore the *flags*.
Do we need to start getting in to details of frame types? Is this really a requirement on the server that the first rectangle for a new context should contain enough data to render every pixel within the rectangle?

2021-02-08 11:26 UTC, CendioOssman commented on rfbproto.rst
> +message, and then display the result.
Might be clearer to merge this with the section stating that there could be multiple frames. I assume the general meaning is that a rectangle can contain lots and lots of frames, but only the final result should be displayed?

2021-02-08 11:26 UTC, CendioOssman commented on rfbproto.rst
> +to decode and display the new frame.
Given the state, how does this interact with other encodings? Are they forbidden from overlapping? I would assume so. But what happens if they overlap? Is that a protocol violation? Or an implicit recent context?

2021-02-08 11:33 UTC, berrange commented on rfbproto.rst
> +I-frame. However, the client should not ignore the *flags*.
We should always explicitly specific the behaviour when the client's Frame Buffer Update Request had  incremental==0. In such a case, I think the server should only send complete frames and not rely on any existing client side state.

2021-02-08 11:35 UTC, CendioOssman commented on rfbproto.rst
> +I-frame. However, the client should not ignore the *flags*.
So specify that it forces the server to do a `ResetAllContexts`?

2021-02-08 11:36 UTC, berrange commented on rfbproto.rst
> +for the longest time.
I wonder what the client can do if it needs to discard one or more of its cached contexts. As written, it can never do this as it can only discard contexts in response to the server flags.

If we declare that a frame buffer update request with incremental==0, always results in complete frames being sent by the server, then we could also use this as a way to reset contexts. eg If server gets a request with incremental==0, could we say that it *must* use  ResetAllContexts in the flags for the subsequent rects it sends ?  Or can we define a separate flag "PermittedContextReset" as a way to indicate to the client that it is permitted to reset its contexts, because the rects are all full.  This would give the client the choice to rebuild - it can skip that choice if it doesn't need to rebuild contexts and save the overhead of doing so

2021-02-08 11:38 UTC, berrange commented on rfbproto.rst
> +I-frame. However, the client should not ignore the *flags*.
That's one option - I only wonder if ResetAllContexts might be too big a hammer if the act of creating a context is a heavy weight operation ? I dont know enough to say for sure either way.

2021-02-08 11:50 UTC, mdevaev commented on rfbproto.rst
> +50           `Pi-KVM H.264 Encoding`_
No. 50 is a free number and is not used by anyone. How can we even register this?

2021-02-08 11:51 UTC, mdevaev commented on rfbproto.rst
> +50           `Pi-KVM H.264 Encoding`_
I don't mind. But you need some name that will be different from the H264 already registered.

2021-02-08 11:52 UTC, CendioOssman commented on rfbproto.rst
> +50           `Pi-KVM H.264 Encoding`_
There's a form you can fill out with IANA and they'll add your entry to their official list.

2021-02-08 11:53 UTC, CendioOssman commented on rfbproto.rst
> +50           `Pi-KVM H.264 Encoding`_
Given that the other one is secret I'm more inclined to change theirs to "RealVNC H.264". First one to write a spec gets to pick the best name. :)

2021-02-08 11:55 UTC, mdevaev commented on rfbproto.rst
> +    =============== ===================================================
Unknown flag values should be ignored by the client.

2021-02-08 11:58 UTC, mdevaev commented on rfbproto.rst
> +for the lowest latency.
Baseline is the simplest format that all encoders and decoders support, but the rest is dependent on the library used. For example, you might want to implement this in noVNC using Broadway JS decoder, but it only supports baseline.

I think that it makes sense to define a number of additional pseudo-encodings, which will mean that not only baseline can be transmitted over this protocol. The client will transmit them and the server will decide what to do with it.

2021-02-08 12:01 UTC, mdevaev commented on rfbproto.rst
> +for the longest time.
In fact, you are highly likely not to need more than a couple. H264 works efficiently for compressing large rectangles (uses its own differential encoding) and so you don't need the old RFB logic for separating them. That is, at the moment, one rectangle is equal to the size of the transmitted screen.

2021-02-08 12:02 UTC, mdevaev commented on rfbproto.rst
> +size will be used to find the decoder context in the client.
What do you mean?

2021-02-08 12:02 UTC, mdevaev commented on rfbproto.rst
> +wants to send an H.264 data, the *FrameBufferUpdate* coordinates and
Okay

2021-02-08 12:03 UTC, mdevaev commented on rfbproto.rst
> +a new one. The **ResetAllContexts** flag deletes all client contexts.
Before, fixed.

2021-02-08 12:04 UTC, mdevaev commented on rfbproto.rst
> +as a control message and apply the *flags*.
No, the transmission can continue. This is just an opportunity for the server to send control flags.

2021-02-08 12:05 UTC, mdevaev commented on rfbproto.rst
> +parsed as a regular H.264 stream.
Plz explain, I don't understand what you mean)

2021-02-08 12:08 UTC, mdevaev commented on rfbproto.rst
> +I-frame. However, the client should not ignore the *flags*.
This is done so that you can have a separate encoder process and a separate server process. Since H264 encoding is a difficult task, it is effective for a single screen on the server to use a common encoder for all clients. The client can connect at any time and sending data will not start from the I-frame. In fact, this is quite normal for streaming differential video, all existing video players are required to handle such a stream.

2021-02-08 12:09 UTC, mdevaev commented on rfbproto.rst
> +message, and then display the result.
Exactly.

2021-02-08 12:11 UTC, mdevaev commented on rfbproto.rst
> +to decode and display the new frame.
I believe that they can overlap and there is nothing wrong with that. Here is a special case: my server implementation sends a normal stream in H264 and JPEG if it wants to display some service text on the screen.

2021-02-08 12:13 UTC, mdevaev commented on rfbproto.rst
> +50           `Pi-KVM H.264 Encoding`_
I suppose we should first refine our specification here

2021-02-08 12:14 UTC, mdevaev commented on rfbproto.rst
> +50           `Pi-KVM H.264 Encoding`_
It is unlikely that the IANA will agree with this, since the person who proposed H264 there is engaged in protocol maintenance

2021-02-08 12:14 UTC, mdevaev commented on rfbproto.rst
> +-------------------------
Fixed

2021-02-08 12:15 UTC, mdevaev commented on rfbproto.rst
> +for transmission over poor communication channels.
Fixed

2021-02-08 12:16 UTC, berrange commented on rfbproto.rst
> +50           `Pi-KVM H.264 Encoding`_
We can't merge this spec without the IANA assignment, and IIUC, IANA doesn't require you to have a spec written.

IOW There's no need to wait, just request the IANA assignment in parallel.

2021-02-08 12:20 UTC, mdevaev commented on rfbproto.rst
> +50           `Pi-KVM H.264 Encoding`_
Okay, let's deal on the name. `Open H.264 Encoding`? Somehow it sounds strange, ambiguous.

In fact, if you use our suggested name, it would be in accordance with the already existing protocols: Tight, RealVNC and other. Why are we worse?)

2021-02-08 12:24 UTC, xornet-sl commented on rfbproto.rst
> +for the longest time.
Actually I think that the number of cached contexts can be defined by implementetion. You really don't need much and we can define some minimal number here, say 10. Implementation can have more, but it must be able to maintain at least 10 (for example). Contexts aren't heavy. In fact it is just a rect buffer + some meta

2021-02-08 12:30 UTC, xornet-sl commented on rfbproto.rst
> +parsed as a regular H.264 stream.
> Can the server send partial frames?

No, the server can encode and send only complete frames. One or more then one, but complete. A client should just send all these frames to H.264 decoder one by one and render the last frame.

2021-02-08 12:34 UTC, mdevaev commented on rfbproto.rst
> +I-frame. However, the client should not ignore the *flags*.
ResetAllContexts  is not a heavy operation and is not even used in my server implementation. We just thought it would be nice to have this flag for third-party implementations. It may be easier for some other server to delete all the contexts at once if it wants to reinitialize for some reason, rather than sending separate messages for each context.

2021-02-08 12:35 UTC, xornet-sl commented on rfbproto.rst
> +I-frame. However, the client should not ignore the *flags*.
Client even can don't mind of frame types and send all the packets to decoder. In such case there will be just glitches on the screen until fisrt I-frame arrived. It is just ok, becouse I-frames come rather often

2021-02-08 16:42 UTC, mdevaev commented on rfbproto.rst
> +50           `Pi-KVM H.264 Encoding`_
QEMU also... I use some QEMU stuff in my server, even though they were clearly not designed for this.

2021-02-09 07:43 UTC, CendioOssman commented on rfbproto.rst
> +50           `Pi-KVM H.264 Encoding`_
And those have been a source of confusion, so we'd rather not repeat that mistake with new things. :)

2021-02-09 07:46 UTC, CendioOssman commented on rfbproto.rst
> +50           `Pi-KVM H.264 Encoding`_
A good opportunity to poke them about the fact that they keep stuff secret. Doesn't clash well with the principle of IANA and IETF. :)

He's not really in a position to reject things. If he tries putting his employer ahead of his role at IANA then we'll have to escalate things. Not that I think he will.

2021-02-09 07:48 UTC, CendioOssman commented on rfbproto.rst
> +50           `Pi-KVM H.264 Encoding`_
If we're sticking to just the baseline profile, then that could be part of the name to clarify things. I.e. "Baseline H.264 Encoding".

2021-02-09 07:48 UTC, CendioOssman commented on rfbproto.rst
> +for the lowest latency.
Fair enough. I assume you've tested baseline and found it sufficient for your use case?

2021-02-09 07:49 UTC, CendioOssman commented on rfbproto.rst
> +for the longest time.
If the number varies then there needs to be some way of the client telling the server how many it supports. Which can get complex. So ideally we find the smallest number that is sufficient and stick with that.

2021-02-09 07:50 UTC, CendioOssman commented on rfbproto.rst
> +size will be used to find the decoder context in the client.
"FrameBufferUpdate" is the entire update with potentially lots of rectangles. So this text should refer to rectangles and not the entire update.

2021-02-09 07:52 UTC, CendioOssman commented on rfbproto.rst
> +as a control message and apply the *flags*.
I meant as in the end of that particular stream. So that the client can free up any context. And then any new rectangles would start fresh with a new context.

Or did you have a different use case in mind here?

2021-02-09 07:53 UTC, CendioOssman commented on rfbproto.rst
> +parsed as a regular H.264 stream.
The frames will be encoded to a stream of bytes. The question is if the server can split that stream up however it likes, or if it can only split on frame boundaries. I think such a requirement should be made explicit in the text.

2021-02-09 07:55 UTC, CendioOssman commented on rfbproto.rst
> +I-frame. However, the client should not ignore the *flags*.
That would violate the VNC protocol. Each update should contain enough to render the screen in a complete, consistent state. I don't think we should go away from that without good reason.

2021-02-09 07:56 UTC, CendioOssman commented on rfbproto.rst
> +to decode and display the new frame.
Wouldn't that break horribly if the next update only contains P-frames? They assume a certain existing contents, which we've now overwritten.

2021-02-09 12:41 UTC, mdevaev commented on rfbproto.rst
> +for the lowest latency.
Yes. It works great.

2021-02-09 12:45 UTC, mdevaev commented on rfbproto.rst
> +for the longest time.
I suggest 255 just for the future, but add a strong recommendation for the client and server to make do with a minimum number of contexts, ideally no more than one for the screen.

2021-02-09 12:47 UTC, mdevaev commented on rfbproto.rst
> +as a control message and apply the *flags*.
Oh, yeah. We're talking about the same thing. Just the lack of data doesn't mean anything in itself, it's all about the flags. A frame with a zero flags and zero data does not have to do anything.

2021-02-09 12:48 UTC, CendioOssman commented on rfbproto.rst
> +for the longest time.
A client needs to be written for what's allowed, not what is common. So if we say 255 here, every client must write their code to handle 255. It doesn't matter if all servers will just use one.

So if less than 255 is sufficient, we should go with that IMHO.

2021-02-09 12:50 UTC, mdevaev commented on rfbproto.rst
> +parsed as a regular H.264 stream.
No, it can't. This doesn't make much sense and it greatly simplifies the implementation. Fixed.

2021-02-09 12:51 UTC, xornet-sl commented on rfbproto.rst
> +as a control message and apply the *flags*.
> I meant as in the end of that particular stream. So that the client can free up any context. And then any new rectangles would start fresh with a new context.
> 
> Or did you have a different use case in mind here?

We don't know any future use cases. it is just a placeholder for them. Right now there are only two flags and in future can be more (for example to change the codec state or something else). It is just a control message. A client should just interpret the flags and do what they mean according this document.

2021-02-09 12:51 UTC, CendioOssman commented on rfbproto.rst
> +as a control message and apply the *flags*.
Alright. Since it is the server that is in control of this, but it is the client that wants it, it would be nice if we recommend a certain behaviour here. E.g. "The server **should** send a rectangle without any data and reset the context when it can in order to let the client free up resources." or something along those lines.

2021-02-09 12:54 UTC, xornet-sl commented on rfbproto.rst
> +parsed as a regular H.264 stream.
> The frames will be encoded to a stream of bytes. The question is if the server can split that stream up however it likes, or if it can only split on frame boundaries. I think such a requirement should be made explicit in the text.

the server can split packets only on the frame boundary. If not that then one screen will come in several update packets. I think it's just a mess. The server encodes a frame at once and it should send it as a solid packet

2021-02-09 13:03 UTC, xornet-sl commented on rfbproto.rst
> +I-frame. However, the client should not ignore the *flags*.
> That would violate the VNC protocol. Each update should contain enough to render the screen in a complete, consistent state. I don't think we should go away from that without good reason.

Ok then. What should client do when it connects to server with async encoder and the client receiving first P-frames (differential ones) in you opinion? I mean we can stick here that the client should show just a blank screen. Or it allowed to render starting glitches util I-frame arrive. It is not about the protocol itself. It is just about handling situation where I-frames have not yet been received.
The reason when server don't send initial I-frame is really good as described by @mdevaev. If one server handles more than one-two clients then encoding process for each of them would be a very hard task. Especially in situations where the server is a tiny embedded system.

2021-02-09 13:04 UTC, mdevaev commented on rfbproto.rst
> +to decode and display the new frame.
No, it works fine. Moreover, the server has several options for how it can handle this situation so that the client has the correct picture.
1. The server can pause the H264 encoding and send the JPEG. It will then resume encoding and send the P-frame. This frame is superimposed on the client context that stored the state of the H264 decoder before receiving the JPEG, and continues to store it further.
2. After JPEG, the server can generate an I-frame. The context will be fully updated.
3. The server can send one of the control flags to reset the context state. This method is used in my server because it does not control the H264 encoding process, but only reads the ready-made stream.

2021-02-09 13:06 UTC, xornet-sl commented on rfbproto.rst
> +to decode and display the new frame.
It is no matter P-frame or I-frame will arrive in the next update. It is even unrelated to encoding. The server should send all overlapped rects in right order to render. With two overlapped JPEGs you overwrite overlapped region too, so the server must send both rects in order to render it right

2021-02-09 13:15 UTC, xornet-sl commented on rfbproto.rst
> +as a control message and apply the *flags*.
> Alright. Since it is the server that is in control of this, but it is the client that wants it, it would be nice if we recommend a certain behaviour here. E.g. "The server **should** send a rectangle without any data and reset the context when it can in order to let the client free up resources." or something along those lines.

Why should we stick with it? It is just a control message inside the H264 protocol to do just *something*. What thing to do is described by flags not by the fact that this packet contains no rect following the header. If flags tell the client "reset the context", ok, client will reset it. If flags will instruct to do something esle in the future - client will do that if it supports it. Features that are supported here can be sent by pseudo-encodings at the start. Right now these flags are mandatory for all clients who will implement H.264 decoder. The next flags (if they will appear) will be described separately and will use standard pseudo-encodings negitiation protocol

2021-02-09 13:21 UTC, mdevaev commented on rfbproto.rst
> +I-frame. However, the client should not ignore the *flags*.
I will add to what has been said. Hypothetically, we can have the server monitor the H264 stream and parse it to see if the current frame is an I or a P-frame. Then the server would receive an UpdateRequest and wait for an I-frame to arrive from the encoder before replying to the client. This will add overhead for the server (it will have to parse the frames and wait) and it will have to remember one more thing about the client state. I think this is an unnecessary complication.

On the other hand, in case of H264, some individual packages for updating the frame no longer contain enough data to display on the screen, since these will only be P-frames, and everything will depend on whether the I-frame is contained in the client. So if you open the package in WireShark you won't see anything interesting there.

The most important reason is that this approach is absolutely natural for H264. The H264 stream allows for frame drops (even an I-frame can be lost) , and absolutely all decoders are able to handle the situation when they do not have an I-frame and get a P-frame. The client can easily process incomplete data and just show a black screen instead of a rectangle, while the server will have to have additional logic for this.

And now I'm not even talking about my own implementation. It doesn't cost me anything to do this since I have information about whether the frame is the key. Here I care about third-party implementations that may use less convenient encoders. They will have to parse the H264 stream, and this is not a very pleasant task, which will also be a waste of hardware resources.

I believe that the RFB here should act as a transport and not try to change the existing semantics established in H264. The encoder should behave normally, and the decoder should do the same. No magic at all.

2021-02-09 13:24 UTC, mdevaev commented on rfbproto.rst
> +to decode and display the new frame.
If we use pseudo-encodings to indicate that the client can work not only with baseline, then we should avoid this word in the name.

2021-02-09 13:25 UTC, mdevaev commented on rfbproto.rst
> +50           `Pi-KVM H.264 Encoding`_
If we want use pseudo-encodings to indicate that the client can work not only with baseline, then we should avoid this word in the name.

2021-02-09 13:29 UTC, mdevaev commented on rfbproto.rst
> +for the longest time.
How much do you offer? If we follow the logic of "one context = one screen", then we limit exactly the number of screens.

2021-02-09 13:40 UTC, mdevaev commented on rfbproto.rst
> +size will be used to find the decoder context in the client.
Gotcha. Fixed.

2021-02-09 14:04 UTC, mdevaev commented on rfbproto.rst
> +50           `Pi-KVM H.264 Encoding`_
To be honest, I don't think there's any hidden intent here. It is possible that the existing numbers are simply reserved and we will be allowed to use them. We'll contact IANA and see what we can do about it.

2021-02-09 15:01 UTC, mdevaev commented on rfbproto.rst
> +    =============== ===================================================
Added a clearer description of this

2021-02-11 00:23 UTC, mdevaev commented on rfbproto.rst
> +50           `Pi-KVM H.264 Encoding`_
@CendioOssman I have a great news! IANA approves `50` for `Open H.264 Encoding`.

![image](https://user-images.githubusercontent.com/416259/107590096-671e8380-6c18-11eb-85f3-67ba0549bbc5.png)

So we can continue our journey.

2021-02-11 00:39 UTC, mdevaev commented on rfbproto.rst
> +50           `Pi-KVM H.264 Encoding`_
Now it has the official name `Open H.264 Encoding`.

2021-02-12 11:22 UTC, CendioOssman commented
Just an FYI, I'm a bit swamped right now so I need a few more days before I have time to check all the new comments here.

2021-02-22 08:48 UTC, mdevaev commented
@CendioOssman boop. I don't want to rush you, but we are already ready to deliver this to our users. I edited the text a bit, adding some clarifications and correcting it to match the style guide. In addition, the pikvm prefixes were removed from the patch in vncviewer to match the current specification.

2021-02-22 11:34 UTC, CendioOssman commented
Sorry, still trying to get to this, but it will likely be a bit longer. This is high on my list, but unfortunately not quite at the top.

2021-03-01 09:33 UTC, CendioOssman commented on rfbproto.rst
> +for the longest time.
RFB has just a single framebuffer, so from that point of view it just needs one. But if one is needed per monitor on the server then that is of course insufficient.

How many have you used in your server?

2021-03-01 09:38 UTC, CendioOssman commented on rfbproto.rst
> +as a control message and apply the *flags*.
The specification should specify not only what is possible, but also recommended behaviour IMHO. This section becomes rather pointless without such a recommendation. Why would a server implementation ever write code that sends a rectangle with no data?

2021-03-01 09:49 UTC, CendioOssman commented on rfbproto.rst
> +I-frame. However, the client should not ignore the *flags*.
But RFB is not just a transport. It is a full display stream, just like H.264. So some extra work and glue is reasonable to expect when trying to get them to work together.

A non-incremental update is much like when a new client shows up. You need to get that client synced up to the stream as well (likely waiting for an I-frame). Until that point you should not start using this new encoding and should rely on other encodings to quickly get the client updating.

If this isn't required by the server then it should be very explicit in the specification that this encoding does not follow that basic principles of RFB that updates are consistent.

(I'd also say that such an exception makes me somewhat sceptical about including it in TigerVNC)

2021-03-01 09:55 UTC, CendioOssman commented on rfbproto.rst
> +to decode and display the new frame.
The problem is that H.264 can base the next frame on the previous. If you modify the pixels outside of the H.264 stream then the encoder and decoder needs to be made aware of those changes. Either by the decoder having a shared state with the RFB framebuffer, or by the RFB code writing back any changes to the H.264 decoder.

I think this places an unreasonable burden on the decoder, so I would recommend taking it out. I would guess hardware decoders would not be able to fulfil this requirement.

Either way the specification needs to be made explicit how overlapping rectangles are handled, given how stateful H.264 is. Either such things are forbidden (and hence a protocol violation), or the client needs to be prepared for them and needs to have a decoder where it can make sure things are in sync.

2021-03-01 09:56 UTC, CendioOssman commented
Most of the stuff looks ready to go. We just need to sort out the semantics around the initial (and non-incremental) updates, and the overlapping. Then we can merge this.

2021-03-01 11:49 UTC, mdevaev commented on rfbproto.rst
> +as a control message and apply the *flags*.
From the point of view of third-party implementations, it may be easier for the server to send a message with some flags, and then send data without flags. Here we want to make life easier for other developers. In addition, other flags may be added in the future that may be useful without data. I just don't want to put restrictions in the protocol where it's not required.

2021-03-01 11:59 UTC, mdevaev commented on rfbproto.rst
> +I-frame. However, the client should not ignore the *flags*.
Either way, we must explicitly declare: or we forbid sending a P-frame without an I-frame (then what should the client do if it receives such a message? this must be explicitly documented), or we resolve it. Yes, I understand that this is a violation of the RFB principles, but it simplifies the implementation of the server (it does not have to monitor the flow), does not require additional effort when implementing the client (all decoders can do this).

I'm not defending my own implementation, but I want to give third-party implementations an easy life. This will allow you to implement fully asynchronous components. In addition, allowing such a situation makes the client more reliable.

Imagine that we are talking about a certain server (not mine), which contains a bug, because of which in some situations it can generate a P-frame before an I-frame. What should the client do? Ignore it? Or, you may disconnect? If it is disconnected, it may not be possible to remotely administer this server.

We are making an extension like this that was not previously available in RFB. We can impose restrictions to preserve the principles, or we can make the protocol unbreakable and easy to implement.

2021-03-01 12:02 UTC, mdevaev commented on rfbproto.rst
> +to decode and display the new frame.
To be honest, I don't quite understand what the problem is here. Let's say the client received the h264 data, decoded it, and then placed it on the screen. After that, the client received the data overlapping with this rectangle in any other format (maybe even h264) and placed it again. The first decoder is based on its internal state, not on what is drawn on the screen, so the arrival of new h264 data will simply cause a redraw of what is already on the screen. As a special case, I have it working with JPEG.

2021-03-01 12:09 UTC, mdevaev commented on rfbproto.rst
> +for the longest time.
Right now I'm using 1. This is because I use a single video capture device that captures a single screen. In the future, I'll add a few more, and we'll need 2 or more. I want this number to be reasonable and limited so that in the next few years it will be enough for everyone.

You wrote here that rfbproto not only describes, but also gives recommendations. Why don't we add that we support 255, and strongly recommend using this as "one context per screen"? I really don't want to be cursed by our descendants when in a few years there will be sort of 8k monitors, for which one hardware encoder will not be enough and you will have to split the entire screen into 8 or 16 contexts due to the limitations of the hardware chips (like some can't handle more than 1080p, or to speed up it's easier to split into several 800x600).

PS: Like 640 kilobytes should be enough for everyone.

2021-03-02 08:47 UTC, mdevaev commented on rfbproto.rst
> +for the longest time.
I have a suggestion on this point. We can not introduce an arbitrary restriction in the form of a certain number, but make their number dynamic. At the same time, make the lower limit.

For example, we can say: at least 64 contexts should be supported. This is enough to support 4 8k screens, each of which will be encoded using 16 hardware encoders that support a maximum of 1080p. The client can support a greater number of contexts. If the server exceeds the number of contexts supported by the client, the client should treat this as an error.

The recommendation includes a strict recommendation to use a minimum number of contexts per screen (ideally, 1, if the hardware allows).

2021-03-02 08:55 UTC, CendioOssman commented on rfbproto.rst
> +as a control message and apply the *flags*.
Okay

2021-03-02 08:57 UTC, mdevaev commented on rfbproto.rst
> +I-frame. However, the client should not ignore the *flags*.
Another thing is the coding errors. This can indeed happen for some reason, and the client should not disconnect if it has received a broken frame. It should wait until a good frame arrives. This is the rule that is adopted in decoding the H264 stream. From this point of view, we can consider the arrival of the P-frame before the I-frame as a special case of an error that should be ignored.

At the same time we can formulate the following two rules:
* The server must return the I-frame as the first data for the new context so that the client can decode something.
* The client must ignore invalid data that it cannot decode.

The combination of these two rules will be consistent with the spirit of the RFB protocol and still provide a reliable connection.

2021-03-02 08:59 UTC, mdevaev commented on rfbproto.rst
> +as a control message and apply the *flags*.
Great! :)

2021-03-02 09:00 UTC, CendioOssman commented on rfbproto.rst
> +I-frame. However, the client should not ignore the *flags*.
To clarify, just P-frame(s) during most updates would be just fine. It's the initial and non-incremental updates that would require an I-frame. And generally clients disconnect if they get something that is not allowed by the protocol. That could mean the server can't be used, but that would be the case for most protocol bugs anyway.

And not guaranteeing an I-frame would make implementing a client **more** difficult if you want to implement a glitch-free experience for the user.

I understand this makes your server implementation easier and more efficient, but it does give a worse user experience IMHO.

2021-03-02 09:03 UTC, CendioOssman commented on rfbproto.rst
> +to decode and display the new frame.
You're assuming the H.264 decoder has a copy of the data on screen, which I would say is not always the case. That would mean duplication that is an inefficiency that many might like to get rid of.

So if that duplication is a required part of this encoding then it should be explicitly stated. If using the displayed data as the decoder state is allowed, then that should also be explicitly stated and likely means forbidding overlapping updates.

2021-03-02 09:05 UTC, CendioOssman commented on rfbproto.rst
> +for the longest time.
I'm not sure I follow. How does the server know if it can use more than 64 contexts in that case?

2021-03-02 09:11 UTC, CendioOssman commented on rfbproto.rst
> +I-frame. However, the client should not ignore the *flags*.
> The client must ignore invalid data that it cannot decode.

This is something that would be completely new in the RFB protocol. I think every other type of invalid data results in a disconnect. RFB was very much not designed with error recovery in mind.

H.264 was designed to operate over lossy transports. RFB requires a guaranteed transport. So there is no need to concern ourselves with such issues in this case here. Trying to compensate for server bugs in the protocol is a fool's errand IMO as such bugs will likely not be recoverable in 99% of the cases anyway. E.g. if the data length field is off by even one byte we'll have no choice but to disconnect as we have no markers to resync on.

2021-03-02 09:11 UTC, mdevaev commented on rfbproto.rst
> +I-frame. However, the client should not ignore the *flags*.
The I-frame must be sent at a periodic interval in any stream, for example, every couple of seconds. To be honest, I'm not sure that you can make a stream only from a P-frame without significant image degradation. Either way, your server should periodically send an I-frame.

At the same time, absolutely any client library is able to handle any decoding errors. The arrival of the P-frame before the I-frame is exactly the same error, quite standard for the H264 decoder, because this situation often happens when live-streaming via UDP.

You can see this for yourself by looking at our PR in TigerVNC. There is no special logic for handling transmission errors, everything works naturally. Whichever library you choose, it will be able to handle this situation.

2021-03-02 09:12 UTC, CendioOssman commented on rfbproto.rst
> +I-frame. However, the client should not ignore the *flags*.
And to re-iterate, this is not a blocker to get things merged. But it needs to be made explicit since it's a big deviation from how RFB normally operates.

2021-03-02 09:15 UTC, mdevaev commented on rfbproto.rst
> +to decode and display the new frame.
The context is not a copy of the displayed data. This is a decoder instance that stores calculated data based on I-frame and P-frame. You can't get rid of them because they are the internals of the H264 library or hardware decoder you are using.

We don't know in what form it is stored inside. But this does resolve the overlap, because even if you modified the image with a different rect, the context (and the data inside it) will remain intact and will be redrawn when a new H264 frame is received.

2021-03-02 09:19 UTC, mdevaev commented on rfbproto.rst
> +I-frame. However, the client should not ignore the *flags*.
I understand. Like you, I want this to be as true to the spirit of the RFB as possible. And yes, of course I want this to be accepted in TigerVNC, otherwise what's the point of it at all :) Do you think the two rules I have proposed are an acceptable compromise?

* The server must return the I-frame as the first data for the new context so that the client can decode something.
* The client must ignore invalid data that it cannot decode.

2021-03-02 09:27 UTC, mdevaev commented on rfbproto.rst
> +I-frame. However, the client should not ignore the *flags*.
Sorry, I didn't notice your second comment.

You are right, an error at the protocol level can lead to the inability to process the message. But this can only happen if the server implementation fails, because we use TCP, which does not lose packets along the way.

The error of the encoder lies on another level, and it may be independent of us. It could be a hardware bug or something like that. The only difference is that error handling for H264 is completely free. In the sense that this is the case where ignoring errors will be easier for any implementation than imposing explicit constraints.

On the other hand, the RFB does not regulate error handling. I think this is an omission of the ancestors :) The abstract client may not be disabled when receiving failed frames. At the same time, if we say that H264 should ignore errors, we will make the client behavior more predictable and the implementation simpler.

2021-03-02 09:30 UTC, mdevaev commented on rfbproto.rst
> +I-frame. However, the client should not ignore the *flags*.
PS: I did encounter hardware coding problems, it looks like "occasionally squares run across the screen". I think the user will not be happy if the client disconnects from the server because of such things.

2021-03-02 09:45 UTC, mdevaev commented on rfbproto.rst
> +for the longest time.
For this case, we can introduce in the future a pseudo-encoding that will report the maximum number of contexts. If there is no pseudo-encoding, then 64 is used.

2021-03-02 10:07 UTC, CendioOssman commented on rfbproto.rst
> +I-frame. However, the client should not ignore the *flags*.
> * The server must return the I-frame as the first data for the new context so that the client can decode something.
> 

Sounds good. And we should also include that a non-incremental data also rests context. The general usage of non-incremental has been if the client needs to drop state, for whatever reasons.

>     * The client must ignore invalid data that it cannot decode.

I'd prefer to leave that out. If implementations want to try to compensate for server bugs then that's up to them. I don't think the specification should require them to do so.

> At the same time, if we say that H264 should ignore errors, we will make the client behavior more predictable and the implementation simpler.

Assuming they are using and already existing fancy H.264 decoder. If someone wants to write a new, simple one. I'm fairly sure they would prefer if error handling is optional. :)

Note that we aren't mandating a disconnect on errors. We've always left it up to the implementations what they want to do if someone isn't following the specification.

2021-03-02 10:08 UTC, CendioOssman commented on rfbproto.rst
> +for the longest time.
Sounds good. :)

2021-03-02 10:11 UTC, mdevaev commented on rfbproto.rst
> +I-frame. However, the client should not ignore the *flags*.
It suits me :) However, can we say in this case that ignoring decoding errors is the recommended, but not the required way to handle them?

2021-03-02 10:16 UTC, mdevaev commented on rfbproto.rst
> +for the longest time.
Cool, fixed.

2021-03-02 10:16 UTC, CendioOssman commented on rfbproto.rst
> +to decode and display the new frame.
I'm not convinced this isn't always the case. If I recall the filtering steps of H.264 were added to avoid having duplicate copies in the decoder as most devices wanted to do filtering before presenting the data.

So, if the is the model we're assuming I think it should be documented. I.e. rectangles using other encodings are allowed to overlap rectangles using the H.264 encoding. But subsequent updates using the H.264 encoding must ignore such other rectangles when decoding and rendering.

2021-03-02 10:17 UTC, CendioOssman commented on rfbproto.rst
> +I-frame. However, the client should not ignore the *flags*.
Fair enough.

2021-03-02 10:24 UTC, mdevaev commented on rfbproto.rst
> +to decode and display the new frame.
Okay, then I'll write like this:

The client should only decode frames based on the internal state of the context and ignore changes in the output buffer that may occur when overlapping of rects. When new data is received, the context will redraw its rectangle and update the previously overlapped data.

2021-03-02 10:34 UTC, mdevaev commented on rfbproto.rst
> +I-frame. However, the client should not ignore the *flags*.
Done. I also added a section on what flags should handle before frames to make the document more clear. This is important for ignoring errors.

2021-03-02 11:00 UTC, mdevaev commented on rfbproto.rst
> +to decode and display the new frame.
Added

2021-03-02 11:06 UTC, mdevaev commented
So, it seems that's all. When you accept this, I will inform the IANA to update the link to the encoding description, fix my server implementation (from the I-frame point of view), and we can take TigerVNC up close. I propose to open the champagne on this occasion :)

2021-03-02 12:21 UTC, CendioOssman commented on rfbproto.rst
> +to decode and display the new frame.
:+1:

2021-03-02 12:22 UTC, CendioOssman approved these changes
Great. Looks good to me. Thanks for working through the feedback. :)

2021-03-02 12:23 UTC, CendioOssman commented
@berrange, do you want to add anything more before we continue?

2021-03-02 13:11 UTC, mdevaev commented
I combined the paragraphs about the number of contexts into one to make it a little clearer.

2021-03-06 09:42 UTC, mdevaev commented
There seems to be no objection :) Right now, our patch for TigerVNC is fully compliant with this specification. The server behavior regarding the I-frame is also fixed.

2021-03-14 10:28 UTC, any1 commented on rfbproto.rst
> +changes in the output buffer that may occur when overlapping of rects.
> ... when overlapping of rects

The wording here is a bit strange.

2021-03-14 11:27 UTC, mdevaev commented on rfbproto.rst
> +changes in the output buffer that may occur when overlapping of rects.
Could you suggest something another? This is not my native language.

2021-03-14 11:39 UTC, any1 commented on rfbproto.rst
> +changes in the output buffer that may occur when overlapping of rects.
Well, the thing is that I'm not exactly sure what this means.

I'm looking into implementing this for [Neat VNC](https://github.com/any1/neatvnc), so I was just reading the spec to see how to do it. This part is probably not important for my implementation, but I thought I'd point it out since I stumbled on it.

2021-03-14 12:08 UTC, mdevaev commented on rfbproto.rst
> +changes in the output buffer that may occur when overlapping of rects.
This means that some H264 decoders can use the output buffer as data storage for subsequent decoding, meaning it can be mutable. If your decoder uses a mutable buffer, then you should make sure that the data will not be modified by other decoders and encodings. If the buffer is immutable, then everything is fine.

2021-03-14 12:10 UTC, mdevaev commented on rfbproto.rst
> +changes in the output buffer that may occur when overlapping of rects.
BTW how did you find out about this encoding? This is a very, very new technology, but I'm glad that there will be another implementation.

2021-03-14 12:20 UTC, any1 commented on rfbproto.rst
> +changes in the output buffer that may occur when overlapping of rects.
I'm subscribed to the rfbproto project, so I get notifications about PRs. I've been intending to create my own h264 encoding, but you seem to have done some of the heavy lifting for us here, which is nice.

2021-03-15 00:06 UTC, mdevaev commented
Could you merge this PR if no one has any objections? Moreover, the developers of Neat VNC server and bVNC client are interested in implementing this specification. I just don't want it hanging in the air, especially considering that all the controversial issues have been fixed and the patch for TigerVNC is also waiting for a review. We successfully tested it and found no problems.

2021-03-16 13:02 UTC, CendioOssman commented
No further comments have been made so we can go ahead and merge this. I'll need to you merge up the commits to something more final though. Please also note that we'd like a signed off line on the commit (see the README).

(and in case you're unfamiliar with Github's PRs you can just do a force push and Github will notice that you squashed things together)

2021-03-16 14:05 UTC, mdevaev commented
@CendioOssman I think I did it.

2021-03-16 14:47 UTC, merged