Add RA2, RA2ne, RA2r, RA2_256, RA2ne_256, RA2r_256 security type
rfbproto/rfbproto pull request #45
Opened 2021-11-28 08:29 UTC by pdlan

It's an initial documentation of RA2 security types for my previous PR https://github.com/novnc/noVNC/pull/1351. Sorry for the late of near 2 years.

2021-11-29 10:11 UTC, CendioOssman requested changes
Nice! Thanks!

2021-11-29 10:11 UTC, CendioOssman commented on rfbproto.rst
> +133         `RA2r_256 <RA2 Security Type_>`_
It would be preferred if this could match the actual heading it refers to. Have you tried some other description? E.g. "RA2 Security Type (RA2r)"?

2021-11-29 10:11 UTC, CendioOssman commented on rfbproto.rst
> +them together.
This is probably very subjective, but I can find this gets a bit messy when all are handled at the same time and you get a exceptions in the text in multiple places.

Did you see how things would look if you handled them more separately? E.g.

```
RA2ne Security type
-------------------

The RA2ne security type is identical to the RA2 security type, except that only the
security handshake is encrypted. The SecurityResult message and all following data
remains unencrypted.
```

2021-11-29 10:11 UTC, CendioOssman commented on rfbproto.rst
> +4               ``U32``      2048    key length in bits
Since the size is explicitly specified I assume this can vary? E.g. this man page says that 2048 is only the default:

https://archive.realvnc.com/products/vnc/documentation/4.3/unix/man/vnckeygen.html

2021-11-29 10:11 UTC, CendioOssman commented on rfbproto.rst
> +::
FYI, you can include those `::` at the end of the preceding paragraph and it will get the same formatting.

2021-11-29 10:11 UTC, CendioOssman commented on rfbproto.rst
> +involves AES-CTR and CMAC. For each message, there is a message header of a
Nice that you managed to figure out what the algorithm was!

2021-11-29 10:11 UTC, CendioOssman commented on rfbproto.rst
> +===================== ============ ====================================
Have you figured out the encoding of these? UTF-8? ISO 8859-1?

2021-11-29 10:16 UTC, CendioOssman requested changes

2021-11-29 10:16 UTC, CendioOssman commented on rfbproto.rst
> +Then the client also sends its public key.
I think it is important to mention that the client has to verify the server's key. Otherwise there is little real security provided here.

2021-11-29 10:18 UTC, CendioOssman requested changes

2021-11-29 10:18 UTC, CendioOssman commented on rfbproto.rst
> +4               ``U32``      2048    key length in bits
Can the client have a key that is of a different size than the server? Give that it is a long lived key I can hope that is the case.

And what happens if the key is too short? Or too long? Does the server send some special message?

2021-11-29 10:29 UTC, CendioOssman requested changes

2021-11-29 10:29 UTC, CendioOssman commented on rfbproto.rst
> +5           `RA2 <RA2 Security Type_>`_
More descriptive names are also preferred, now that we know how these work. I would guess the "RA2" is short for "RSA Authentication".

2021-11-29 19:59 UTC, pdlan commented on rfbproto.rst
> +5           `RA2 <RA2 Security Type_>`_
From [this document](https://static.realvnc.com/media/documents/realvnc-rfb-protocol-security-analysis.pdf) it seems that RA2 stands for "RSA with AES version 2". I will use the name "RSA-AES Authentication" instead.

2021-11-29 19:59 UTC, pdlan commented on rfbproto.rst
> +4               ``U32``      2048    key length in bits
Yes I confirmed that the sizes can be different.

2021-11-29 20:01 UTC, pdlan commented on rfbproto.rst
> +4               ``U32``      2048    key length in bits
Yes, I tried to use the keys of the sizes from 512 bits to 8192 bits and the RealVNC client accepted all of them.

2021-11-30 09:30 UTC, CendioOssman commented on rfbproto.rst
> +5           `RA2 <RA2 Security Type_>`_
Sounds good! :+1:

That document also mentions an RA4. Anything you've looked at?

2021-11-30 09:38 UTC, CendioOssman requested changes

2021-11-30 09:38 UTC, CendioOssman commented on rfbproto.rst
> +13          `RSA-AES Two-step Security Type (RA2r) <RSA-AES Two-step Security Type_>`_
We don't need to keep the short forms now that they have different heading. Avoids having to have the `<>` syntax.

2021-11-30 09:38 UTC, CendioOssman commented on rfbproto.rst
> -6           RA2ne
129, 130 and 133 should also be removed from the list.

2021-11-30 09:38 UTC, CendioOssman commented on rfbproto.rst
> +are big-endian integers. If the key length is too small or too big,
I guess they are unsigned as well since there is no padding for an extra leading 0?

2021-11-30 14:18 UTC, CendioOssman commented on rfbproto.rst
> +13          `RSA-AES Two-step Security Type (RA2r) <RSA-AES Two-step Security Type_>`_
Ah, sorry. I missed that some things were still grouped.

I think splitting is fine. This is a reference documentation, so some things naturally get a bit repetitive. :)

I assume these extra chapters are extremely short? It was just a swap of SHA-1 for SHA-256, right?

2021-11-30 17:03 UTC, pdlan commented on rfbproto.rst
> +5           `RA2 <RA2 Security Type_>`_
From my observation RealVNC can only use RA2 with RFB3.8. RA4 is used for RFB4+, which is not documented at all.

2021-12-03 08:21 UTC, CendioOssman requested changes
Looks great! Thanks!

Please squash the commits, finalize the commit message and add a signed-off line and I'll go ahead and merge this.

2021-12-08 09:04 UTC, pdlan commented
Hi @CendioOssman, any update on this?

2021-12-08 09:50 UTC, CendioOssman commented
Sorry, I missed that your last update (not sure if GitHub sent a notification?). I'll have a look now.

2021-12-08 09:51 UTC, merged

2021-12-08 09:57 UTC, pdlan commented
Great!I think GitHub might also have not sent the notification of the noVNC's PR. You could also have a look at that if it's convenient for you.