Draft: Document ExtendedMouseButtons pseudo-encoding
rfbproto/rfbproto pull request #57
Opened 2024-07-03 11:22 UTC by CendioHalim

This pseudo-encoding adds support for additional mouse buttons, most notably the forward and backward mouse buttons.
* Open PR: https://github.com/TigerVNC/tigervnc/pull/1711
* [Current development branch / implementation](https://github.com/CendioHalim/tigervnc/tree/mouse-button-support)
  * Development has continued in another branch, no open PR for it as of yet

2024-07-03 11:25 UTC, CendioHalim commented
The pseudo-encoding has been registered with [IANA](https://www.iana.org/assignments/rfb/rfb.xhtml#rfb-3) and has the assignment:

 **-316 	ExtendedMouseButtons**

2024-07-23 00:12 UTC, samhed approved these changes

2024-07-23 08:21 UTC, CendioHalim commented on rfbproto.rst
> +
This is already written, the last paragraph at the bottom:
```
Currently, bit 1 in the *extended-button-mask* corresponds to the
forward mouse button, and bit 2 corresponds to the back mouse button.
The remaining 6 bits are reserved.
```

Do you think there should be a similar text added here as well, part of the PointerEvent chapter?

2024-07-23 08:33 UTC, berrange commented on rfbproto.rst
> +
Oh, that's easy to miss at a glance. If we present the information in each chapter as a table rather than prose, I think it'd be more visible. ie in this chapter add

```
=== ==========================
Bit   Button
=== ==========================
0   Left
1   Middle
2   Right 
3   Wheel Up
4   Wheel Down
5   Wheel Left
6   Wheel Right
7   ExtendedPointerEvent Marker
=== =========================
```

And in the latter (new) chapter  add

```
=== ==========================
Bit   Button
=== ==========================
0   Forward
1   Back
2   Reserved 
3   Reserved
4   Reserved
5   Reserved
6   Reserved
7   Reserved
=== =========================
```

2024-07-23 08:35 UTC, CendioHalim commented on rfbproto.rst
> +
That's a good point. It's much easier and quicker to read when presented as a table

2024-07-24 14:58 UTC, berrange commented on rfbproto.rst
> +========= =============================================================
This is good, but this commit is missing the companion table under "PointerEvent"

2024-07-25 09:35 UTC, CendioHalim commented on rfbproto.rst
> +========= =============================================================
Added a table to "PointerEvent" as well, but I'm not sure the placement is the best. What do you think?

2024-07-25 09:40 UTC, berrange commented on rfbproto.rst
> +========= =============================================================
It is ok by me.

2024-07-29 14:58 UTC, CendioOssman requested changes
Looks promising! Some clarifications and we should be good.

2024-07-29 14:58 UTC, CendioOssman commented on rfbproto.rst
> +------------------------------------
Most of this chapter describes the contents of the `PointerEvent` message. I think it's better if those portions are in that message's chapter, as that's where people will look for how it should be handled.

I would suggest keeping just the first paragraph. Possibly also just referring to it as an "extended PointerEvent message" and defining what that means in the other chapter.

2024-07-29 14:58 UTC, CendioOssman commented on rfbproto.rst
> +`PointerEvent`_  message. The marker bit is the 7th bit of
The 7th bit is bit 6, which is probably not what you mean. :)

Given the system here, I would suggest calling it the highest bit. Least risk of confusion.

2024-07-29 14:58 UTC, CendioOssman commented on rfbproto.rst
> +
You may not need to be this verbose. It's sufficient to clearly state how the messages are expected to look like. Then it's up to the implementation how to send/receive them.

2024-07-29 14:58 UTC, CendioOssman commented on rfbproto.rst
> +ignored by the server.
As discussed elsewhere, this may need a warning/clarification on what we consider "forward" and "backward".

I suggested a dive in to the USB specification to increase the clarity of this mess. Has that been done?

2024-07-29 14:58 UTC, CendioOssman commented on rfbproto.rst
> +7         Reserved
It's best to specify what reserved means for the client and server. I would suggest clients are required to send 0, and servers are required to ignore them.

2024-07-29 14:58 UTC, CendioOssman commented on rfbproto.rst
> +bit to 0.
I think we need to consider old/current clients more here.

What happens if a client sends the high bit set, but no ExtendedMouseButtons pseudo-encoding?

And clients supporting ExtendedMouseButtons likely need to be forced to send the high bit 0 until they know the server supports it?

2024-07-29 17:35 UTC, RokerHRO commented
I'd favour a more flexible and extensible approach, that would also work for so-called "gaming" mice with lots of additional buttons (that might be mapped to keybord shortcts at server side) and for other USB input devices such as styluses or digitizer tablets that are able to report ''strength'' of pressure etc.
 
Maybe a look into the USB HID specification would help, so we don't have to re-invent the wheel, because USB HID already covers other extended "event input" devices.

2024-07-29 17:53 UTC, any1 commented
> I'd favour a more flexible and extensible approach

Yes, let's also do that, but this is fine as is.

> Maybe a look into the USB HID specification

That's actually a pretty good idea. USB is really just a transport for HID. I know of at least one non-USB use of HID: Miracast passes raw HID events (and descriptors) back to the presenter. This is mainly useful with touch panels.

I look forward to seeing proposals for VNC-HID. :)

2024-07-30 07:06 UTC, CendioOssman commented
> I'd favour a more flexible and extensible approach, that would also work for so-called "gaming" mice with lots of additional buttons (that might be mapped to keybord shortcts at server side)

That is something we thought of as well. Turns out, these mice (at least not the ones we have access to) do not send mouse events. They send keyboard events for all those extra buttons. :/

My guess would be because Windows doesn't have a convenient interface for anything more than the back and forward button, so why send hardware events that most applications cannot easily use.

> and for other USB input devices such as styluses or digitizer tablets that are able to report ''strength'' of pressure etc.

That would be nice, but is a much bigger project. Might also require bidirectional signalling to reconfigure things. 

Let's not have those grander ambitions block fixing a common use case like browser interaction.

2024-07-30 09:36 UTC, CendioHalim commented on rfbproto.rst
> +bit to 0.
> What happens if a client sends the high bit set, but no ExtendedMouseButtons pseudo-encoding

I tested this, using a client that sent a button mask with the high bit set, with other servers (https://github.com/TigerVNC/tigervnc/pull/1711#issuecomment-2145069550).

I should probably test against more implementations to see if there is anything that breaks, but from what I've tested, setting the high bit only affected the RealVNC server, which corresponded with a back button press.

> And clients supporting ExtendedMouseButtons likely need to be forced to send the high bit 0 until they know the server supports it?

Yes, I will add that.

2024-07-30 10:54 UTC, CendioOssman commented on rfbproto.rst
> +bit to 0.
> I tested this, using a client that sent a button mask with the high bit set, with other servers ([TigerVNC/tigervnc#1711 (comment)](https://github.com/TigerVNC/tigervnc/pull/1711#issuecomment-2145069550)).

What I meant was, what happens when you do this to a server that *supports* this extension? It might expect a second byte that never comes.

2024-09-10 05:43 UTC, CendioHalim commented on rfbproto.rst
> +7         Reserved
Good point!

2024-09-10 05:45 UTC, CendioHalim commented on rfbproto.rst
> +bit to 0.
I've updated the spec so that servers that support this extension ignore the marker bit unless the client also supports it. Clients are also required to send the marker bit as 0 if they support the extension, until the server has indicated that it also supports the extension.

2024-09-10 05:47 UTC, CendioHalim commented on rfbproto.rst
> +ignored by the server.
As discussed, I agree it's a good idea. I haven't looked at the USB HID specification yet.

2024-09-12 07:01 UTC, RokerHRO commented
Am I right: this protocol extension enables only 2 more mouse buttons (with pre-defined meanings)?

So if a future client wants to support a super fancy mouse with another cool button there is _no way_ for a client to use the "reserved" bits for it nor to negotiate with the server the presence and the meaning of the remaining bits. Another crude "pseudo encoding" hack has to be defined in that case.

2024-09-12 09:38 UTC, CendioHalim commented
> Am I right: this protocol extension enables only 2 more mouse buttons (with pre-defined meanings)?

Correct. There are two motivations for this:

1. Simplicity - This is very easy to implement on both the client and server side.
2. QoL - For me personally, this addition is a huge QoL improvement for VNC. While a more general solution would be very cool to have, it would require significant effort to implement. The work needed to implement vs. actual usability, with the current solution, is very high in my opinion.

> So if a future client wants to support a super fancy mouse with another cool button there is _no way_ for a client to use the "reserved" bits for it nor to negotiate with the server the presence and the meaning of the remaining bits. Another crude "pseudo encoding" hack has to be defined in that case.

The point of leaving the remaining bits reserved is to leave room for future additions to this pseudo-encoding. Future additions could be either more buttons, or other hacks for a more general approach (or another pseudo-encoding entirely). 

Having the unused bits reserved as of now should make it easier to preserve backwards compatibility.

2024-09-20 12:09 UTC, CendioOssman commented on rfbproto.rst
> +1               ``U8``                          *extended-buttons-mask*
I don't think we have any precedence of having optional fields like this in a description. I'm worried someone might read this too casually and think this field is always present.

What are your thoughts on keeping the original table, and then having an almost duplicate table showing the extended mode?

2024-09-20 12:11 UTC, CendioOssman commented on rfbproto.rst
> +========= =============================================================
This table duplicates what's written earlier. It would probably be best to merge things in some way.

2024-09-20 12:17 UTC, CendioOssman commented on rfbproto.rst
> +7         ExtendedMouseButtons Marker
This is only well-defined with this new extension. It is probably best to mention that it has no good historical definition. Or did we find any client or server that used it? I would assume it would be the "back" button if used.

2024-09-20 12:19 UTC, CendioOssman commented on rfbproto.rst
> +can be set to 1.
**must** be set to 1 if this extra byte is used.

2024-09-20 12:21 UTC, CendioOssman commented on rfbproto.rst
> +this pseudo-encoding is enabled, the highest bit in the *button-mask*
I'm concerned that this phrasing could be interpreted as it being sufficient to do `SetEncodings` with `ExtendedMouseButtons`.

Perhaps use the phrase "this extension is enabled" and readers will need to look at the other chapter for details?

2024-09-20 12:24 UTC, CendioOssman commented on rfbproto.rst
> +Clients that don't support this pseudo-encoding must set the highest bit
We can't retroactively change client behaviour.

2024-09-20 12:25 UTC, CendioOssman commented on rfbproto.rst
> +ignore the marker bit if the client does not support it. If the server
"it" here is ambiguous. Should probably explicitly state "this extension".

2024-09-20 12:25 UTC, CendioOssman commented on rfbproto.rst
> +ignore the marker bit if the client does not support it. If the server
Is this perhaps a bit harsh? If the client has not signalled support, then shouldn't legacy behaviour persist?

2024-09-20 12:27 UTC, CendioOssman commented on rfbproto.rst
> +to 0.
I think it's better to state "Until the client knows the server supports this extension...". It is not just about legacy servers, but also a race until the handshake is complete.

2024-09-20 12:28 UTC, CendioOssman commented on rfbproto.rst
> +byte button mask.
Part of this can probably be removed, as it should be clear from the table. In order to keep the section from getting too long.

2024-09-20 12:30 UTC, CendioOssman commented on rfbproto.rst
> +normal `PointerEvent`_ message and, no further action is needed.
It is probably best to explicitly state that any high bits are assumed to be zero when this happens. Otherwise, it becomes unclear what it means to send an extended event with high mouse buttons pressed, followed by a normal event.

2024-09-20 12:32 UTC, CendioOssman commented on rfbproto.rst
> +which contains the *extended-buttons-mask*.
I wonder if this is a bit too step-by-step and hence gets a bit wordy and difficult to read. We should describe the wire format, not how the code should be written.

2024-09-20 12:33 UTC, CendioOssman commented on rfbproto.rst
> +which contains the *extended-buttons-mask*.
Somewhere in here, it needs to be explicit that this depends on whether the client has advertised support for the extension or not. Otherwise, a high bit does not mean that there is more data.

2024-09-20 12:33 UTC, CendioOssman commented on rfbproto.rst
> +backward mouse button, and bit 1 corresponds to the forward mouse
This is redundant with the table

2024-09-20 12:34 UTC, CendioOssman commented on rfbproto.rst
> +client and ignored by the server.
This is good and should still be included. It allows defining those bits at a later date.

2024-09-20 12:37 UTC, CendioOssman commented on rfbproto.rst
> +BTN_LABEL_PROP_BTN_EXTRA respectively.
Those are rather internal constants and are probably not too useful to most people.

I think it is sufficient to write something generic that there has historically been some confusion on which buttons are Back/Forward. And perhaps instead define them by behaviour. I.e. what they do in applications.

And since it is an implementation hint, it might be best as a note.

2024-09-20 12:38 UTC, CendioOssman commented on rfbproto.rst
> +7         0
`0` suggests that it will always be the only value. "Reserved" is more clear what is going on here.

2024-09-20 12:41 UTC, CendioOssman commented on rfbproto.rst
> +pseudo-encoding. When a client has received the matching response from
*When* will the server send this? It's best to be explicit.

2024-09-24 14:59 UTC, CendioHalim commented on rfbproto.rst
> +can be set to 1.
Hmm, my reasoning was that you don't **have** to send an extended `PointerEvent` message unless you have to (to save bandwidth or whatever).  The way it is worded now is a bit ambiguous.

Changing it to **must** would make things easier, and the only drawback is that an additional byte is sent per `PointerEvent` message. 

What do you think is best? Forcing all  `PointerEvent`  messages to be extended with this pseudo-encoding, or only forcing it if you want to send the extra byte?

2024-09-24 15:18 UTC, CendioHalim commented on rfbproto.rst
> +7         ExtendedMouseButtons Marker
I tested the following servers:
  * TurboVNC
  * x0vncserver
  * RealVNC
  * libvncserver
    * x11vnc
 
Out of these, only x0vncserver responded to the 7th bit being set, and I was able to navigate "back" on Firefox/Chrome.
 
 I tested the following clients with an Xvnc server that looks at the 7th bit:
   * TurboVNC
   * TightVNC
   * RealVNC
   * Remmina
   * noVNC

Out of these, only RealVNC responded to clicking on the back button.

2024-09-24 15:35 UTC, CendioHalim commented on rfbproto.rst
> +7         ExtendedMouseButtons Marker
I guess this means that the current wording:
```While a normal `PointerEvent`_ uses 7 of the 8 available bits```
is incorrect. The back button is nothing that has ever been a part of the specification, my guess is that the edge cases I've seen are purely coincidental.

2024-09-25 09:37 UTC, CendioHalim commented on rfbproto.rst
> +bit to 0.
I thought about this one more time, and I think that the behaviour should be the following:

| Server pseudo-encoding   | Client pseudo-encoding | Behaviour |
| ------------------------------------- | ----------------------------------- | --------------- |
| No                                         | No                                        | Client sends 1 byte, highest bit **can** be set to indicate back button. <br> Server reads 1 byte, **don't** ignore highest bit, **can** interpret highest bit as back button.|
| Yes                                         | No                                        | Client sends 1 byte, highest bit **can** be set to indicate back button. <br> Server reads 1 byte, **don't** ignore highest bit, **can** interpret highest bit as back button.|
| No                                         | Yes                                        | Client sends 1 byte, highest bit **can** be set to indicate back button. <br> Server reads 1 byte, **don't** ignore highest bit, **can** interpret highest bit as back button.|
| Yes                                         | Yes                                        | Client sends 1 byte, highest bit **can** be set to indicate extended `PointerEvent`.  If highest bit is set, another byte **must** be sent.<br> Server reads 1 byte and **must** read highest bit. If highest bit is set, server **must** read another byte.|

This way, we should preserve the old behaviour except for in the case where both the client and server have indicated the pseudo-encoding support, and the client sets the highest bit.

Servers should **only** expect another byte if the client has indicated pseudo-encoding support, and the highest bit is set.

2024-09-26 09:22 UTC, CendioOssman requested changes

2024-09-26 09:22 UTC, CendioOssman commented on rfbproto.rst
> +The *ExtendedMouseButtons* pseudo-encoding provides support for 8
Technically, 7 additional?

2024-09-26 09:22 UTC, CendioOssman commented on rfbproto.rst
> +0         Back
I guess we leave the button 8 for the standard message undefined for now?

2024-09-26 09:22 UTC, CendioOssman commented on rfbproto.rst
> +
It's still not explicitly stated what happens if you mix standard and extended messages.

2024-09-26 09:36 UTC, berrange commented on rfbproto.rst
> +
From the earlier text 

```
 When this pseudo-encoding is enabled, the highest bit in 
the *button-mask* can be set to one, which marks the `PointerEvent`_ 
message as an extended `PointerEvent`_ message"
```

I interpreted it was permitted to mix both standard & extended messages at the clients discretion, since the word `can` was used rather than `must`. Lets make the intention explicit though.

2024-09-26 09:40 UTC, berrange commented on rfbproto.rst
> +0         Back
Hmm, interesting question.   What happens if we have a future situation where some VNC server/client that's unaware of this extension, defines a mapping for button 8 in the standard message. If it later wants to use the extended message, it can't use button 8 in the standard message anymore, as that bit is used to indicate that extended message. We would nee to re-map it into the extended message I guess ?

2024-09-26 10:28 UTC, CendioOssman commented on rfbproto.rst
> +0         Back
I think that ship has sailed, given that RealVNC and x0vncserver already have some behaviour for that bit. So it's more that we haven't explicitly documented it.

2024-09-26 10:32 UTC, berrange commented on rfbproto.rst
> +0         Back
Hmm, awkward. I can't help thinking that rather than having the encoding alter the semantics of the PointerEvent message, it would be simpler if we requested assignment of a "ExtendedPointerEvent" message, and then just defined its button-mask as a `u16`. That way we wouldn't have to assign magic semantics to bit 8, which clash with pre-existing usage of bit 8.

2024-09-26 10:38 UTC, CendioOssman commented on rfbproto.rst
> +0         Back
Indeed. But the namespace for messages is a lot smaller than for encodings. So they idea here was to avoid an allocation if possible.

2024-09-26 10:39 UTC, CendioOssman commented on rfbproto.rst
> +0         Back
And it's not like that button is somehow lost. It just gets shifted up to the lowest bit in the extended byte.

2024-09-26 11:33 UTC, CendioHalim commented on rfbproto.rst
> +
> I interpreted it was permitted to mix both standard & extended messages at the clients discretion, since the word `can` was used rather than `must`. Lets make the intention explicit though.

That was my reasoning, but yeah this could be described more explicitly.

2024-09-26 11:39 UTC, CendioHalim commented on rfbproto.rst
> +0         Back
> Hmm, interesting question. What happens if we have a future situation where some VNC server/client that's unaware of this extension, defines a mapping for button 8 in the standard message. If it later wants to use the extended message, it can't use button 8 in the standard message anymore, as that bit is used to indicate that extended message. We would nee to re-map it into the extended message I guess ?

> And it's not like that button is somehow lost. It just gets shifted up to the lowest bit in the extended byte.

Indeed, button 8 would be assigned to the first bit in the extended mask.

The only thing that we break with this pseudo-encoding is that clients that want to enable this feature are **not** allowed to send bit 8 when sending normal `PointerEvent` messages. The damage is quite minimal in my opinion, as there are barely any servers/clients that use bit 8 anyway and the bit's meaning is not defined in the protocol.

2024-09-26 11:40 UTC, CendioHalim commented on rfbproto.rst
> +0         Back
> I guess we leave the button 8 for the standard message undefined for now?

I don't feel confident that we can/should define button 8, undefined is probably best.

2024-09-26 11:44 UTC, CendioHalim commented on rfbproto.rst
> +
Or perhaps using the word `may`, which is used many times in the specification already? It also matches [RFC2119](https://datatracker.ietf.org/doc/html/rfc2119) more closely.

2024-09-26 11:46 UTC, CendioHalim commented on rfbproto.rst
> +The *ExtendedMouseButtons* pseudo-encoding provides support for 8
Hmm, depends. If we specify bit 8 in the normal message as undefined, then we do technically get 8 more bits to play with.

2024-09-27 13:52 UTC, CendioHalim commented on rfbproto.rst
> +7         ExtendedMouseButtons Marker
> Out of these, only RealVNC responded to clicking on the back button.

My mistake, what I saw was that RealVNC server `vncserver-x11`, (not `vncserver-virtual`) responded on clicking the back button.

2024-10-21 11:20 UTC, CendioOssman requested changes
Looks pretty good. Some clarifications with the last changes could be good, then we can merge.

2024-11-18 12:06 UTC, CendioOssman approved these changes

2024-11-18 12:18 UTC, merged